server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name 47.76.106.57;

    ssl_certificate /etc/letsencrypt/live/47.76.106.57/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/47.76.106.57/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    include /etc/nginx/default.d/portra.conf;
}
