import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../AuthContext.jsx'
import { adminApi } from '../../api/adminApi.js'
import { buildModerationReasonBody, completeAdminMutation, openAdminDetail, resetAdminPage } from './adminData.js'
import { AdminEmptyState } from './components/AdminEmptyState.jsx'
import { AdminHallCard } from './components/AdminHallCard.jsx'
import { AdminModeBanner } from './components/AdminModeBanner.jsx'
import { ModerationReasonDialog } from './components/ModerationReasonDialog.jsx'

const statuses = ['ALL', 'VISIBLE', 'HIDDEN', 'REPORTED']
const asPage = (value, fallback) => Array.isArray(value) ? { records: value, ...fallback, total: value.length } : { records: value?.records || [], page: value?.page || fallback.page, size: value?.size || fallback.size, total: value?.total || 0 }
function Pager({ data, onPage }) { const pages = Math.max(1, Math.ceil(data.total / data.size)); return <nav className="admin-pagination"><button type="button" disabled={data.page <= 1} onClick={() => onPage(data.page - 1)}>上一页</button><span>{data.page} / {pages}</span><button type="button" disabled={data.page >= pages} onClick={() => onPage(data.page + 1)}>下一页</button></nav> }

export function AdminHallPage() {
  const { currentUser } = useAuth(); const navigate = useNavigate(); const requestId = useRef(0)
  const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState('ALL'); const [page, setPage] = useState(1); const [data, setData] = useState({ records: [], page: 1, size: 20, total: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [detail, setDetail] = useState(null); const [action, setAction] = useState({ item: null, kind: '', reason: '', submitting: false, error: '' })
  const load = useCallback(() => adminApi.listHallItems({ page, size: 20, status, ...(keyword.trim() ? { keyword: keyword.trim() } : {}) }, currentUser), [currentUser, keyword, page, status])
  const refresh = useCallback(async () => { const token = ++requestId.current; const result = asPage(await load(), { page, size: 20 }); if (token === requestId.current) setData(result); return result }, [load, page])
  useEffect(() => { const token = ++requestId.current; setLoading(true); setError(''); setData({ records: [], page, size: 20, total: 0 }); load().then(value => { if (token === requestId.current) setData(asPage(value, { page, size: 20 })) }).catch(e => { if (token === requestId.current) { setData({ records: [], page, size: 20, total: 0 }); setError(e.message || '大厅列表加载失败。') } }).finally(() => { if (token === requestId.current) setLoading(false) }) }, [load, page])
  const updateFilters = (nextStatus = status, nextKeyword = keyword) => { setPage(resetAdminPage()); setStatus(nextStatus); setKeyword(nextKeyword) }
  async function submit() { let body; try { body = buildModerationReasonBody(action.reason) } catch (e) { setAction(v => ({ ...v, error: e.message })); return }; setAction(v => ({ ...v, submitting: true, error: '' })); try { const type = String(action.item.type).toUpperCase(); const outcome = await completeAdminMutation(() => action.kind === 'take-down' ? adminApi.takeDownHallItem(type, action.item.id, body, currentUser) : adminApi.restoreHallItem(type, action.item.id, body, currentUser), () => Promise.all([refresh(), adminApi.dashboard(currentUser)])); setAction({ item: null, kind: '', reason: '', submitting: false, error: '' }); setSuccess(outcome.refreshed ? '操作已成功，列表已刷新。' : '操作已成功，但刷新失败；请刷新列表确认。') } catch (e) { setAction(v => ({ ...v, submitting: false, error: e.message || '处理失败。' })) } }
  return <main className="admin-page"><AdminModeBanner title="大厅管理" description="读取真实管理员大厅列表并执行内容治理。" /><section className="admin-hall-toolbar"><label>搜索<input value={keyword} onChange={e => updateFilters(status, e.target.value)} /></label><div>{statuses.map(value => <button className={status === value ? 'admin-filter-button is-active' : 'admin-filter-button'} type="button" key={value} onClick={() => updateFilters(value)}>{value}</button>)}</div></section>{success ? <div className="admin-complaint-success">{success}</div> : null}{error ? <div className="admin-inline-error">{error}<button type="button" onClick={() => refresh().catch(() => {})}>重试</button></div> : null}{loading ? <AdminEmptyState title="正在读取大厅…" /> : null}{!loading && !error && !data.records.length ? <AdminEmptyState title="暂无符合条件的内容" /> : null}<section className="admin-hall-grid">{data.records.map(item => <AdminHallCard key={`${item.type}-${item.id}`} item={item} onOpen={openAdminDetail(setDetail, item)} onOpenPublisher={item.publisherId ? () => navigate(`/admin/users/${item.publisherId}`) : undefined} onTakeDown={() => setAction({ item, kind: 'take-down', reason: '', submitting: false, error: '' })} onRestore={() => setAction({ item, kind: 'restore', reason: '', submitting: false, error: '' })} />)}</section><Pager data={data} onPage={setPage} />{detail ? <section className="admin-report-legend" role="dialog"><h2>{detail.title || '内容详情'}</h2><p>{detail.description || '暂无内容说明。'}</p><p>发布者 #{detail.publisherId} · {detail.moderationStatus}</p><button type="button" onClick={() => setDetail(null)}>关闭</button></section> : null}<ModerationReasonDialog open={Boolean(action.item)} title={action.kind === 'take-down' ? '确认下架' : '确认恢复展示'} description={action.error || '请填写处理原因。'} value={action.reason} required submitting={action.submitting} onChange={reason => setAction(v => ({ ...v, reason, error: '' }))} onCancel={() => !action.submitting && setAction({ item: null, kind: '', reason: '', submitting: false, error: '' })} onConfirm={submit} /></main>
}
