import { useCallback, useEffect, useRef, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { useAuth } from '../../AuthContext.jsx'
import { adminApi } from '../../api/adminApi.js'
import { buildModerationReasonBody, completeAdminMutation, openAdminDetail, resetAdminPage } from './adminData.js'
import { AdminEmptyState } from './components/AdminEmptyState.jsx'
import { AdminModeBanner } from './components/AdminModeBanner.jsx'
import { AdminMomentCard } from './components/AdminMomentCard.jsx'
import { ModerationReasonDialog } from './components/ModerationReasonDialog.jsx'

const statuses = ['ALL', 'VISIBLE', 'HIDDEN', 'REPORTED']; const asPage = (v, f) => Array.isArray(v) ? { records: v, ...f, total: v.length } : { records: v?.records || [], page: v?.page || f.page, size: v?.size || f.size, total: v?.total || 0 }
function Pager({ data, onPage }) { const pages = Math.max(1, Math.ceil(data.total / data.size)); return <nav className="admin-pagination"><button type="button" disabled={data.page <= 1} onClick={() => onPage(data.page - 1)}>上一页</button><span>{data.page} / {pages}</span><button type="button" disabled={data.page >= pages} onClick={() => onPage(data.page + 1)}>下一页</button></nav> }
export function AdminFeedPage() {
  const { currentUser } = useAuth(); const navigate = useNavigate(); const requestId = useRef(0); const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState('ALL'); const [page, setPage] = useState(1); const [data, setData] = useState({ records: [], page: 1, size: 20, total: 0 }); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [detail, setDetail] = useState(null); const [action, setAction] = useState({ moment: null, kind: '', reason: '', submitting: false, error: '' })
  const load = useCallback(() => adminApi.listMoments({ page, size: 20, status, ...(keyword.trim() ? { keyword: keyword.trim() } : {}) }, currentUser), [currentUser, keyword, page, status])
  const refresh = useCallback(async () => { const token = ++requestId.current; const result = asPage(await load(), { page, size: 20 }); if (token === requestId.current) setData(result); return result }, [load, page])
  useEffect(() => { const token = ++requestId.current; setLoading(true); setError(''); setData({ records: [], page, size: 20, total: 0 }); load().then(v => { if (token === requestId.current) setData(asPage(v, { page, size: 20 })) }).catch(e => { if (token === requestId.current) { setData({ records: [], page, size: 20, total: 0 }); setError(e.message || '动态列表加载失败。') } }).finally(() => { if (token === requestId.current) setLoading(false) }) }, [load, page])
  const filter = (nextStatus = status, nextKeyword = keyword) => { setPage(resetAdminPage()); setStatus(nextStatus); setKeyword(nextKeyword) }
  async function submit() { let body; try { body = buildModerationReasonBody(action.reason) } catch (e) { setAction(v => ({ ...v, error: e.message })); return }; setAction(v => ({ ...v, submitting: true, error: '' })); try { const outcome = await completeAdminMutation(() => action.kind === 'take-down' ? adminApi.takeDownMoment(action.moment.momentId, body, currentUser) : adminApi.restoreMoment(action.moment.momentId, body, currentUser), () => Promise.all([refresh(), adminApi.dashboard(currentUser)])); setAction({ moment: null, kind: '', reason: '', submitting: false, error: '' }); setSuccess(outcome.refreshed ? '操作已成功，列表已刷新。' : '操作已成功，但刷新失败；请刷新列表确认。') } catch (e) { setAction(v => ({ ...v, submitting: false, error: e.message || '处理失败。' })) } }
  return <main className="admin-page"><AdminModeBanner title="动态管理" description="读取真实管理员动态列表；互动计数仅供查看。" /><section className="admin-feed-toolbar"><label>搜索<input value={keyword} onChange={e => filter(status, e.target.value)} /></label><div>{statuses.map(value => <button key={value} type="button" className={status === value ? 'admin-filter-button is-active' : 'admin-filter-button'} onClick={() => filter(value)}>{value}</button>)}</div></section>{success ? <div className="admin-complaint-success">{success}</div> : null}{error ? <div className="admin-inline-error">{error}<button type="button" onClick={() => refresh().catch(() => {})}>重试</button></div> : null}{loading ? <AdminEmptyState title="正在读取动态…" /> : null}{!loading && !error && !data.records.length ? <AdminEmptyState title="暂无符合条件的动态" /> : null}<section className="admin-feed-list">{data.records.map(moment => <AdminMomentCard key={moment.momentId} moment={moment} onOpen={openAdminDetail(setDetail, moment)} onOpenAuthor={() => navigate(`/admin/users/${moment.authorId}`)} onTakeDown={() => setAction({ moment, kind: 'take-down', reason: '', submitting: false, error: '' })} onRestore={() => setAction({ moment, kind: 'restore', reason: '', submitting: false, error: '' })} />)}</section><Pager data={data} onPage={setPage} />{detail ? <section className="admin-report-legend" role="dialog"><h2>{detail.title || '动态详情'}</h2><p>{detail.content || '暂无文字内容。'}</p><p>作者 #{detail.authorId} · {detail.moderationStatus}</p><button type="button" onClick={() => setDetail(null)}>关闭</button></section> : null}<ModerationReasonDialog open={Boolean(action.moment)} title={action.kind === 'take-down' ? '确认下架动态' : '确认恢复展示'} description={action.error || '请填写处理原因。'} value={action.reason} required submitting={action.submitting} onChange={reason => setAction(v => ({ ...v, reason, error: '' }))} onCancel={() => !action.submitting && setAction({ moment: null, kind: '', reason: '', submitting: false, error: '' })} onConfirm={submit} /></main>
}
