import { useCallback, useEffect, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../../AuthContext.jsx'
import { adminApi } from '../../api/adminApi.js'
import { buildUserStatusBody, completeAdminMutation, parseExactUserId } from './adminData.js'
import { AdminActionBar } from './components/AdminActionBar.jsx'
import { AdminEmptyState } from './components/AdminEmptyState.jsx'
import { AdminModeBanner } from './components/AdminModeBanner.jsx'
import { ModerationReasonDialog } from './components/ModerationReasonDialog.jsx'

export function AdminUserProfilePage() {
  const { userId: rawId } = useParams(); const userId = parseExactUserId(rawId); const { currentUser } = useAuth(); const navigate = useNavigate(); const [user, setUser] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [retryKey, setRetryKey] = useState(0); const [action, setAction] = useState({ status: '', reason: '', submitting: false, error: '' })
  const load = useCallback(async () => { if (!userId) throw new Error('用户 ID 无效。'); return adminApi.getUserAdminProfile(userId, currentUser) }, [currentUser, userId])
  useEffect(() => { let active = true; setLoading(true); setError(''); load().then(value => active && setUser(value)).catch(e => active && setError(e.message || '用户资料加载失败。')).finally(() => active && setLoading(false)); return () => { active = false } }, [load, retryKey])
  async function submit() { let body; try { body = buildUserStatusBody(action.status, action.reason) } catch (e) { setAction(v => ({ ...v, error: e.message })); return }; setAction(v => ({ ...v, submitting: true, error: '' })); try { const outcome = await completeAdminMutation(() => adminApi.updateUserStatus(userId, body, currentUser), async () => { const [detail] = await Promise.all([load(), adminApi.dashboard(currentUser)]); setUser(detail) }); setUser(outcome.response); setAction({ status: '', reason: '', submitting: false, error: '' }); setSuccess(outcome.refreshed ? '账号状态已成功更新。' : '账号状态已成功更新，但刷新失败；请刷新确认。') } catch (e) { setAction(v => ({ ...v, submitting: false, error: e.message || '账号状态更新失败。' })) } }
  const self = Number(currentUser?.userId) === Number(userId)
  return <main className="admin-page"><AdminModeBanner title="用户主页" description="管理员用户详情仅来自管理员接口。" />{success ? <div className="admin-complaint-success">{success}</div> : null}{loading ? <AdminEmptyState title="正在读取用户…" /> : null}{error ? <div className="admin-inline-error">{error}<button type="button" onClick={() => setRetryKey(v => v + 1)}>重试</button></div> : null}{user ? <><section className="admin-user-profile-hero"><div><h2>{user.nickname || `用户 #${userId}`}</h2><p>用户 #{user.userId} · {user.currentRole} · {user.status}</p><p>{user.bio || '暂无简介'}</p></div><dl className="admin-user-facts"><div><dt>待处理举报</dt><dd>{user.pendingReportCount}</dd></div><div><dt>举报总数</dt><dd>{user.totalReportCount}</dd></div><div><dt>公开内容</dt><dd>{(user.publicDemandCount || 0) + (user.publicServicePackageCount || 0) + (user.publicMomentCount || 0)}</dd></div></dl></section><section className="admin-user-profile-actions"><AdminActionBar actions={[{ key: 'back', label: '返回用户列表', onClick: () => navigate('/admin/users') }, { key: 'disable', label: '限制账号', danger: true, disabled: self || user.status === 'DISABLED', hint: self ? '不能限制自己' : '', onClick: () => setAction({ status: 'DISABLED', reason: '', submitting: false, error: '' }) }, { key: 'restore', label: '解除限制', disabled: self || user.status !== 'DISABLED', hint: self ? '不能限制自己' : '', onClick: () => setAction({ status: 'ACTIVE', reason: '', submitting: false, error: '' }) }]} /></section></> : null}<ModerationReasonDialog open={Boolean(action.status)} title={action.status === 'DISABLED' ? '确认限制账号' : '确认解除限制'} description={action.error || '请填写处理原因。'} value={action.reason} required submitting={action.submitting} onChange={reason => setAction(v => ({ ...v, reason, error: '' }))} onCancel={() => !action.submitting && setAction({ status: '', reason: '', submitting: false, error: '' })} onConfirm={submit} /></main>
}
